# Generated by Django 5.1.2 on 2025-06-30 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('hospital', '0002_patient_is_checked_in_waitinglistentry'),
        ('labs', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.appointment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='inpatient_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.inpatientrecord'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labs.labtest'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.prescription'),
        ),
    ]
