# Generated by Django 5.1.2 on 2025-07-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_appointment_invoice_inpatient_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='insurance_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('cash', 'Cash'), ('insurance', 'Insurance')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
