# Generated by Django 5.1.2 on 2025-07-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
