# Generated by Django 5.1.2 on 2025-07-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='max_stock',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
