# Generated by Django 5.1.2 on 2025-07-09 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_delete_prescription'),
        ('pharmacy', '0003_alter_prescriptionitem_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='notes',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(related_name='prescriptions', through='pharmacy.PrescriptionItem', to='pharmacy.medicine'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.patient'),
        ),
    ]
