# Generated by Django 5.1.2 on 2025-07-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
