# Generated by Django 5.1.2 on 2025-07-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_patient_assigned_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatientrecord',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inpatientrecord',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inpatientrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
