# Generated by Django 5.1.2 on 2025-07-09 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatientrecord',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['receptionist', 'pharmacist']}, related_name='inpatient_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
