# Generated by Django 5.1.2 on 2025-07-09 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_alter_inpatientrecord_assigned_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
