# Generated by Django 5.1.2 on 2025-07-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_labtest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
