# Generated by Django 5.1.2 on 2025-07-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_labtest_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='report_sent',
            field=models.BooleanField(default=False),
        ),
    ]
